/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SaljareRouteImport } from './routes/saljare'
import { Route as SaljHjalpRouteImport } from './routes/salj-hjalp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as KopRouteImport } from './routes/kop'
import { Route as KontoRouteImport } from './routes/konto'
import { Route as BeloningarRouteImport } from './routes/beloningar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AktiveraRouteImport } from './routes/aktivera'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VIdRouteImport } from './routes/v.$id'

const SaljareRoute = SaljareRouteImport.update({
  id: '/saljare',
  path: '/saljare',
  getParentRoute: () => rootRouteImport,
} as any)
const SaljHjalpRoute = SaljHjalpRouteImport.update({
  id: '/salj-hjalp',
  path: '/salj-hjalp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const KopRoute = KopRouteImport.update({
  id: '/kop',
  path: '/kop',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoRoute = KontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const BeloningarRoute = BeloningarRouteImport.update({
  id: '/beloningar',
  path: '/beloningar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AktiveraRoute = AktiveraRouteImport.update({
  id: '/aktivera',
  path: '/aktivera',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VIdRoute = VIdRouteImport.update({
  id: '/v/$id',
  path: '/v/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aktivera': typeof AktiveraRoute
  '/auth': typeof AuthRoute
  '/beloningar': typeof BeloningarRoute
  '/konto': typeof KontoRoute
  '/kop': typeof KopRoute
  '/reset-password': typeof ResetPasswordRoute
  '/salj-hjalp': typeof SaljHjalpRoute
  '/saljare': typeof SaljareRoute
  '/v/$id': typeof VIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aktivera': typeof AktiveraRoute
  '/auth': typeof AuthRoute
  '/beloningar': typeof BeloningarRoute
  '/konto': typeof KontoRoute
  '/kop': typeof KopRoute
  '/reset-password': typeof ResetPasswordRoute
  '/salj-hjalp': typeof SaljHjalpRoute
  '/saljare': typeof SaljareRoute
  '/v/$id': typeof VIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aktivera': typeof AktiveraRoute
  '/auth': typeof AuthRoute
  '/beloningar': typeof BeloningarRoute
  '/konto': typeof KontoRoute
  '/kop': typeof KopRoute
  '/reset-password': typeof ResetPasswordRoute
  '/salj-hjalp': typeof SaljHjalpRoute
  '/saljare': typeof SaljareRoute
  '/v/$id': typeof VIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aktivera'
    | '/auth'
    | '/beloningar'
    | '/konto'
    | '/kop'
    | '/reset-password'
    | '/salj-hjalp'
    | '/saljare'
    | '/v/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/aktivera'
    | '/auth'
    | '/beloningar'
    | '/konto'
    | '/kop'
    | '/reset-password'
    | '/salj-hjalp'
    | '/saljare'
    | '/v/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aktivera'
    | '/auth'
    | '/beloningar'
    | '/konto'
    | '/kop'
    | '/reset-password'
    | '/salj-hjalp'
    | '/saljare'
    | '/v/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AktiveraRoute: typeof AktiveraRoute
  AuthRoute: typeof AuthRoute
  BeloningarRoute: typeof BeloningarRoute
  KontoRoute: typeof KontoRoute
  KopRoute: typeof KopRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SaljHjalpRoute: typeof SaljHjalpRoute
  SaljareRoute: typeof SaljareRoute
  VIdRoute: typeof VIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saljare': {
      id: '/saljare'
      path: '/saljare'
      fullPath: '/saljare'
      preLoaderRoute: typeof SaljareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salj-hjalp': {
      id: '/salj-hjalp'
      path: '/salj-hjalp'
      fullPath: '/salj-hjalp'
      preLoaderRoute: typeof SaljHjalpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kop': {
      id: '/kop'
      path: '/kop'
      fullPath: '/kop'
      preLoaderRoute: typeof KopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beloningar': {
      id: '/beloningar'
      path: '/beloningar'
      fullPath: '/beloningar'
      preLoaderRoute: typeof BeloningarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktivera': {
      id: '/aktivera'
      path: '/aktivera'
      fullPath: '/aktivera'
      preLoaderRoute: typeof AktiveraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$id': {
      id: '/v/$id'
      path: '/v/$id'
      fullPath: '/v/$id'
      preLoaderRoute: typeof VIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AktiveraRoute: AktiveraRoute,
  AuthRoute: AuthRoute,
  BeloningarRoute: BeloningarRoute,
  KontoRoute: KontoRoute,
  KopRoute: KopRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SaljHjalpRoute: SaljHjalpRoute,
  SaljareRoute: SaljareRoute,
  VIdRoute: VIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
