/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SverigeRouteImport } from './routes/sverige'
import { Route as SkogRouteImport } from './routes/skog'
import { Route as SkapaLagRouteImport } from './routes/skapa-lag'
import { Route as SaljareRouteImport } from './routes/saljare'
import { Route as SaljHjalpRouteImport } from './routes/salj-hjalp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PriserRouteImport } from './routes/priser'
import { Route as KopRouteImport } from './routes/kop'
import { Route as KontoRouteImport } from './routes/konto'
import { Route as IntegritetRouteImport } from './routes/integritet'
import { Route as HjalpRouteImport } from './routes/hjalp'
import { Route as CertPreviewRouteImport } from './routes/cert-preview'
import { Route as BeloningarRouteImport } from './routes/beloningar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AktiveraRouteImport } from './routes/aktivera'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VIdRouteImport } from './routes/v.$id'
import { Route as AdminMallarRouteImport } from './routes/admin.mallar'
import { Route as ApiPublicUnsubscribeRouteImport } from './routes/api/public/unsubscribe'
import { Route as ApiPublicSiteEventRouteImport } from './routes/api/public/site-event'
import { Route as ApiPublicPushNotifyRouteImport } from './routes/api/public/push-notify'
import { Route as AdminMallarIdRouteImport } from './routes/admin.mallar.$id'
import { Route as ApiPublicHooksWeeklyBackupRouteImport } from './routes/api/public/hooks/weekly-backup'
import { Route as ApiPublicHooksThemeTestMailRouteImport } from './routes/api/public/hooks/theme-test-mail'
import { Route as ApiPublicHooksTeamWeeklyReportRouteImport } from './routes/api/public/hooks/team-weekly-report'
import { Route as ApiPublicHooksDeliverScheduledCertsRouteImport } from './routes/api/public/hooks/deliver-scheduled-certs'

const SverigeRoute = SverigeRouteImport.update({
  id: '/sverige',
  path: '/sverige',
  getParentRoute: () => rootRouteImport,
} as any)
const SkogRoute = SkogRouteImport.update({
  id: '/skog',
  path: '/skog',
  getParentRoute: () => rootRouteImport,
} as any)
const SkapaLagRoute = SkapaLagRouteImport.update({
  id: '/skapa-lag',
  path: '/skapa-lag',
  getParentRoute: () => rootRouteImport,
} as any)
const SaljareRoute = SaljareRouteImport.update({
  id: '/saljare',
  path: '/saljare',
  getParentRoute: () => rootRouteImport,
} as any)
const SaljHjalpRoute = SaljHjalpRouteImport.update({
  id: '/salj-hjalp',
  path: '/salj-hjalp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PriserRoute = PriserRouteImport.update({
  id: '/priser',
  path: '/priser',
  getParentRoute: () => rootRouteImport,
} as any)
const KopRoute = KopRouteImport.update({
  id: '/kop',
  path: '/kop',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoRoute = KontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetRoute = IntegritetRouteImport.update({
  id: '/integritet',
  path: '/integritet',
  getParentRoute: () => rootRouteImport,
} as any)
const HjalpRoute = HjalpRouteImport.update({
  id: '/hjalp',
  path: '/hjalp',
  getParentRoute: () => rootRouteImport,
} as any)
const CertPreviewRoute = CertPreviewRouteImport.update({
  id: '/cert-preview',
  path: '/cert-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const BeloningarRoute = BeloningarRouteImport.update({
  id: '/beloningar',
  path: '/beloningar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AktiveraRoute = AktiveraRouteImport.update({
  id: '/aktivera',
  path: '/aktivera',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VIdRoute = VIdRouteImport.update({
  id: '/v/$id',
  path: '/v/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMallarRoute = AdminMallarRouteImport.update({
  id: '/mallar',
  path: '/mallar',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicUnsubscribeRoute = ApiPublicUnsubscribeRouteImport.update({
  id: '/api/public/unsubscribe',
  path: '/api/public/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSiteEventRoute = ApiPublicSiteEventRouteImport.update({
  id: '/api/public/site-event',
  path: '/api/public/site-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushNotifyRoute = ApiPublicPushNotifyRouteImport.update({
  id: '/api/public/push-notify',
  path: '/api/public/push-notify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMallarIdRoute = AdminMallarIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminMallarRoute,
} as any)
const ApiPublicHooksWeeklyBackupRoute =
  ApiPublicHooksWeeklyBackupRouteImport.update({
    id: '/api/public/hooks/weekly-backup',
    path: '/api/public/hooks/weekly-backup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksThemeTestMailRoute =
  ApiPublicHooksThemeTestMailRouteImport.update({
    id: '/api/public/hooks/theme-test-mail',
    path: '/api/public/hooks/theme-test-mail',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTeamWeeklyReportRoute =
  ApiPublicHooksTeamWeeklyReportRouteImport.update({
    id: '/api/public/hooks/team-weekly-report',
    path: '/api/public/hooks/team-weekly-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDeliverScheduledCertsRoute =
  ApiPublicHooksDeliverScheduledCertsRouteImport.update({
    id: '/api/public/hooks/deliver-scheduled-certs',
    path: '/api/public/hooks/deliver-scheduled-certs',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aktivera': typeof AktiveraRoute
  '/auth': typeof AuthRoute
  '/beloningar': typeof BeloningarRoute
  '/cert-preview': typeof CertPreviewRoute
  '/hjalp': typeof HjalpRoute
  '/integritet': typeof IntegritetRoute
  '/konto': typeof KontoRoute
  '/kop': typeof KopRoute
  '/priser': typeof PriserRoute
  '/reset-password': typeof ResetPasswordRoute
  '/salj-hjalp': typeof SaljHjalpRoute
  '/saljare': typeof SaljareRoute
  '/skapa-lag': typeof SkapaLagRoute
  '/skog': typeof SkogRoute
  '/sverige': typeof SverigeRoute
  '/admin/mallar': typeof AdminMallarRouteWithChildren
  '/v/$id': typeof VIdRoute
  '/admin/mallar/$id': typeof AdminMallarIdRoute
  '/api/public/push-notify': typeof ApiPublicPushNotifyRoute
  '/api/public/site-event': typeof ApiPublicSiteEventRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/public/hooks/deliver-scheduled-certs': typeof ApiPublicHooksDeliverScheduledCertsRoute
  '/api/public/hooks/team-weekly-report': typeof ApiPublicHooksTeamWeeklyReportRoute
  '/api/public/hooks/theme-test-mail': typeof ApiPublicHooksThemeTestMailRoute
  '/api/public/hooks/weekly-backup': typeof ApiPublicHooksWeeklyBackupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aktivera': typeof AktiveraRoute
  '/auth': typeof AuthRoute
  '/beloningar': typeof BeloningarRoute
  '/cert-preview': typeof CertPreviewRoute
  '/hjalp': typeof HjalpRoute
  '/integritet': typeof IntegritetRoute
  '/konto': typeof KontoRoute
  '/kop': typeof KopRoute
  '/priser': typeof PriserRoute
  '/reset-password': typeof ResetPasswordRoute
  '/salj-hjalp': typeof SaljHjalpRoute
  '/saljare': typeof SaljareRoute
  '/skapa-lag': typeof SkapaLagRoute
  '/skog': typeof SkogRoute
  '/sverige': typeof SverigeRoute
  '/admin/mallar': typeof AdminMallarRouteWithChildren
  '/v/$id': typeof VIdRoute
  '/admin/mallar/$id': typeof AdminMallarIdRoute
  '/api/public/push-notify': typeof ApiPublicPushNotifyRoute
  '/api/public/site-event': typeof ApiPublicSiteEventRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/public/hooks/deliver-scheduled-certs': typeof ApiPublicHooksDeliverScheduledCertsRoute
  '/api/public/hooks/team-weekly-report': typeof ApiPublicHooksTeamWeeklyReportRoute
  '/api/public/hooks/theme-test-mail': typeof ApiPublicHooksThemeTestMailRoute
  '/api/public/hooks/weekly-backup': typeof ApiPublicHooksWeeklyBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aktivera': typeof AktiveraRoute
  '/auth': typeof AuthRoute
  '/beloningar': typeof BeloningarRoute
  '/cert-preview': typeof CertPreviewRoute
  '/hjalp': typeof HjalpRoute
  '/integritet': typeof IntegritetRoute
  '/konto': typeof KontoRoute
  '/kop': typeof KopRoute
  '/priser': typeof PriserRoute
  '/reset-password': typeof ResetPasswordRoute
  '/salj-hjalp': typeof SaljHjalpRoute
  '/saljare': typeof SaljareRoute
  '/skapa-lag': typeof SkapaLagRoute
  '/skog': typeof SkogRoute
  '/sverige': typeof SverigeRoute
  '/admin/mallar': typeof AdminMallarRouteWithChildren
  '/v/$id': typeof VIdRoute
  '/admin/mallar/$id': typeof AdminMallarIdRoute
  '/api/public/push-notify': typeof ApiPublicPushNotifyRoute
  '/api/public/site-event': typeof ApiPublicSiteEventRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/public/hooks/deliver-scheduled-certs': typeof ApiPublicHooksDeliverScheduledCertsRoute
  '/api/public/hooks/team-weekly-report': typeof ApiPublicHooksTeamWeeklyReportRoute
  '/api/public/hooks/theme-test-mail': typeof ApiPublicHooksThemeTestMailRoute
  '/api/public/hooks/weekly-backup': typeof ApiPublicHooksWeeklyBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aktivera'
    | '/auth'
    | '/beloningar'
    | '/cert-preview'
    | '/hjalp'
    | '/integritet'
    | '/konto'
    | '/kop'
    | '/priser'
    | '/reset-password'
    | '/salj-hjalp'
    | '/saljare'
    | '/skapa-lag'
    | '/skog'
    | '/sverige'
    | '/admin/mallar'
    | '/v/$id'
    | '/admin/mallar/$id'
    | '/api/public/push-notify'
    | '/api/public/site-event'
    | '/api/public/unsubscribe'
    | '/api/public/hooks/deliver-scheduled-certs'
    | '/api/public/hooks/team-weekly-report'
    | '/api/public/hooks/theme-test-mail'
    | '/api/public/hooks/weekly-backup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/aktivera'
    | '/auth'
    | '/beloningar'
    | '/cert-preview'
    | '/hjalp'
    | '/integritet'
    | '/konto'
    | '/kop'
    | '/priser'
    | '/reset-password'
    | '/salj-hjalp'
    | '/saljare'
    | '/skapa-lag'
    | '/skog'
    | '/sverige'
    | '/admin/mallar'
    | '/v/$id'
    | '/admin/mallar/$id'
    | '/api/public/push-notify'
    | '/api/public/site-event'
    | '/api/public/unsubscribe'
    | '/api/public/hooks/deliver-scheduled-certs'
    | '/api/public/hooks/team-weekly-report'
    | '/api/public/hooks/theme-test-mail'
    | '/api/public/hooks/weekly-backup'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aktivera'
    | '/auth'
    | '/beloningar'
    | '/cert-preview'
    | '/hjalp'
    | '/integritet'
    | '/konto'
    | '/kop'
    | '/priser'
    | '/reset-password'
    | '/salj-hjalp'
    | '/saljare'
    | '/skapa-lag'
    | '/skog'
    | '/sverige'
    | '/admin/mallar'
    | '/v/$id'
    | '/admin/mallar/$id'
    | '/api/public/push-notify'
    | '/api/public/site-event'
    | '/api/public/unsubscribe'
    | '/api/public/hooks/deliver-scheduled-certs'
    | '/api/public/hooks/team-weekly-report'
    | '/api/public/hooks/theme-test-mail'
    | '/api/public/hooks/weekly-backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AktiveraRoute: typeof AktiveraRoute
  AuthRoute: typeof AuthRoute
  BeloningarRoute: typeof BeloningarRoute
  CertPreviewRoute: typeof CertPreviewRoute
  HjalpRoute: typeof HjalpRoute
  IntegritetRoute: typeof IntegritetRoute
  KontoRoute: typeof KontoRoute
  KopRoute: typeof KopRoute
  PriserRoute: typeof PriserRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SaljHjalpRoute: typeof SaljHjalpRoute
  SaljareRoute: typeof SaljareRoute
  SkapaLagRoute: typeof SkapaLagRoute
  SkogRoute: typeof SkogRoute
  SverigeRoute: typeof SverigeRoute
  VIdRoute: typeof VIdRoute
  ApiPublicPushNotifyRoute: typeof ApiPublicPushNotifyRoute
  ApiPublicSiteEventRoute: typeof ApiPublicSiteEventRoute
  ApiPublicUnsubscribeRoute: typeof ApiPublicUnsubscribeRoute
  ApiPublicHooksDeliverScheduledCertsRoute: typeof ApiPublicHooksDeliverScheduledCertsRoute
  ApiPublicHooksTeamWeeklyReportRoute: typeof ApiPublicHooksTeamWeeklyReportRoute
  ApiPublicHooksThemeTestMailRoute: typeof ApiPublicHooksThemeTestMailRoute
  ApiPublicHooksWeeklyBackupRoute: typeof ApiPublicHooksWeeklyBackupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sverige': {
      id: '/sverige'
      path: '/sverige'
      fullPath: '/sverige'
      preLoaderRoute: typeof SverigeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skog': {
      id: '/skog'
      path: '/skog'
      fullPath: '/skog'
      preLoaderRoute: typeof SkogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skapa-lag': {
      id: '/skapa-lag'
      path: '/skapa-lag'
      fullPath: '/skapa-lag'
      preLoaderRoute: typeof SkapaLagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saljare': {
      id: '/saljare'
      path: '/saljare'
      fullPath: '/saljare'
      preLoaderRoute: typeof SaljareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salj-hjalp': {
      id: '/salj-hjalp'
      path: '/salj-hjalp'
      fullPath: '/salj-hjalp'
      preLoaderRoute: typeof SaljHjalpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priser': {
      id: '/priser'
      path: '/priser'
      fullPath: '/priser'
      preLoaderRoute: typeof PriserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kop': {
      id: '/kop'
      path: '/kop'
      fullPath: '/kop'
      preLoaderRoute: typeof KopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritet': {
      id: '/integritet'
      path: '/integritet'
      fullPath: '/integritet'
      preLoaderRoute: typeof IntegritetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hjalp': {
      id: '/hjalp'
      path: '/hjalp'
      fullPath: '/hjalp'
      preLoaderRoute: typeof HjalpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cert-preview': {
      id: '/cert-preview'
      path: '/cert-preview'
      fullPath: '/cert-preview'
      preLoaderRoute: typeof CertPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beloningar': {
      id: '/beloningar'
      path: '/beloningar'
      fullPath: '/beloningar'
      preLoaderRoute: typeof BeloningarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktivera': {
      id: '/aktivera'
      path: '/aktivera'
      fullPath: '/aktivera'
      preLoaderRoute: typeof AktiveraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$id': {
      id: '/v/$id'
      path: '/v/$id'
      fullPath: '/v/$id'
      preLoaderRoute: typeof VIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mallar': {
      id: '/admin/mallar'
      path: '/mallar'
      fullPath: '/admin/mallar'
      preLoaderRoute: typeof AdminMallarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/unsubscribe': {
      id: '/api/public/unsubscribe'
      path: '/api/public/unsubscribe'
      fullPath: '/api/public/unsubscribe'
      preLoaderRoute: typeof ApiPublicUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site-event': {
      id: '/api/public/site-event'
      path: '/api/public/site-event'
      fullPath: '/api/public/site-event'
      preLoaderRoute: typeof ApiPublicSiteEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-notify': {
      id: '/api/public/push-notify'
      path: '/api/public/push-notify'
      fullPath: '/api/public/push-notify'
      preLoaderRoute: typeof ApiPublicPushNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mallar/$id': {
      id: '/admin/mallar/$id'
      path: '/$id'
      fullPath: '/admin/mallar/$id'
      preLoaderRoute: typeof AdminMallarIdRouteImport
      parentRoute: typeof AdminMallarRoute
    }
    '/api/public/hooks/weekly-backup': {
      id: '/api/public/hooks/weekly-backup'
      path: '/api/public/hooks/weekly-backup'
      fullPath: '/api/public/hooks/weekly-backup'
      preLoaderRoute: typeof ApiPublicHooksWeeklyBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/theme-test-mail': {
      id: '/api/public/hooks/theme-test-mail'
      path: '/api/public/hooks/theme-test-mail'
      fullPath: '/api/public/hooks/theme-test-mail'
      preLoaderRoute: typeof ApiPublicHooksThemeTestMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/team-weekly-report': {
      id: '/api/public/hooks/team-weekly-report'
      path: '/api/public/hooks/team-weekly-report'
      fullPath: '/api/public/hooks/team-weekly-report'
      preLoaderRoute: typeof ApiPublicHooksTeamWeeklyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/deliver-scheduled-certs': {
      id: '/api/public/hooks/deliver-scheduled-certs'
      path: '/api/public/hooks/deliver-scheduled-certs'
      fullPath: '/api/public/hooks/deliver-scheduled-certs'
      preLoaderRoute: typeof ApiPublicHooksDeliverScheduledCertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminMallarRouteChildren {
  AdminMallarIdRoute: typeof AdminMallarIdRoute
}

const AdminMallarRouteChildren: AdminMallarRouteChildren = {
  AdminMallarIdRoute: AdminMallarIdRoute,
}

const AdminMallarRouteWithChildren = AdminMallarRoute._addFileChildren(
  AdminMallarRouteChildren,
)

interface AdminRouteChildren {
  AdminMallarRoute: typeof AdminMallarRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMallarRoute: AdminMallarRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AktiveraRoute: AktiveraRoute,
  AuthRoute: AuthRoute,
  BeloningarRoute: BeloningarRoute,
  CertPreviewRoute: CertPreviewRoute,
  HjalpRoute: HjalpRoute,
  IntegritetRoute: IntegritetRoute,
  KontoRoute: KontoRoute,
  KopRoute: KopRoute,
  PriserRoute: PriserRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SaljHjalpRoute: SaljHjalpRoute,
  SaljareRoute: SaljareRoute,
  SkapaLagRoute: SkapaLagRoute,
  SkogRoute: SkogRoute,
  SverigeRoute: SverigeRoute,
  VIdRoute: VIdRoute,
  ApiPublicPushNotifyRoute: ApiPublicPushNotifyRoute,
  ApiPublicSiteEventRoute: ApiPublicSiteEventRoute,
  ApiPublicUnsubscribeRoute: ApiPublicUnsubscribeRoute,
  ApiPublicHooksDeliverScheduledCertsRoute:
    ApiPublicHooksDeliverScheduledCertsRoute,
  ApiPublicHooksTeamWeeklyReportRoute: ApiPublicHooksTeamWeeklyReportRoute,
  ApiPublicHooksThemeTestMailRoute: ApiPublicHooksThemeTestMailRoute,
  ApiPublicHooksWeeklyBackupRoute: ApiPublicHooksWeeklyBackupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
