/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as KopRouteImport } from './routes/kop'
import { Route as KontoRouteImport } from './routes/konto'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VIdRouteImport } from './routes/v.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const KopRoute = KopRouteImport.update({
  id: '/kop',
  path: '/kop',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoRoute = KontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VIdRoute = VIdRouteImport.update({
  id: '/v/$id',
  path: '/v/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/konto': typeof KontoRoute
  '/kop': typeof KopRoute
  '/reset-password': typeof ResetPasswordRoute
  '/v/$id': typeof VIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/konto': typeof KontoRoute
  '/kop': typeof KopRoute
  '/reset-password': typeof ResetPasswordRoute
  '/v/$id': typeof VIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/konto': typeof KontoRoute
  '/kop': typeof KopRoute
  '/reset-password': typeof ResetPasswordRoute
  '/v/$id': typeof VIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/konto'
    | '/kop'
    | '/reset-password'
    | '/v/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/konto'
    | '/kop'
    | '/reset-password'
    | '/v/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/konto'
    | '/kop'
    | '/reset-password'
    | '/v/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  KontoRoute: typeof KontoRoute
  KopRoute: typeof KopRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VIdRoute: typeof VIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kop': {
      id: '/kop'
      path: '/kop'
      fullPath: '/kop'
      preLoaderRoute: typeof KopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$id': {
      id: '/v/$id'
      path: '/v/$id'
      fullPath: '/v/$id'
      preLoaderRoute: typeof VIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  KontoRoute: KontoRoute,
  KopRoute: KopRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VIdRoute: VIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
